server.port=8080
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

# \u751F\u4EA7\u8005


# \u6D88\u8D39\u8005
# \u5355\u6B21\u63A8\u9001\u6D88\u606F\u6570\u91CF
spring.rabbitmq.listener.simple.prefetch=5
# \u6D88\u8D39\u8005\u7684\u6D88\u8D39\u7EBF\u7A0B\u6570\u91CF
spring.rabbitmq.listener.simple.concurrency=1
# \u6D88\u8D39\u8005\u7684\u6700\u5927\u7EBF\u7A0B\u6570\u91CF
spring.rabbitmq.listener.simple.max-concurrency=10
# \u6279\u5904\u7406\u5927\u5C0F
spring.rabbitmq.listener.simple.batch-size=4


spring.rabbitmq.listener.simple.acknowledge-mode=none



# 2.6\u4EE5\u4E0A\u7248\u672CSpringBoot\u96C6\u6210Swagger2\u8981\u4FEE\u6539\u914D\u7F6E
spring.mvc.pathmatch.matching-strategy=ant_path_matcher